### ISSUE TITLE
[Request] Add multiple language support

### ISSUE THREAD

**Issue by wikijm** [inputstick/KP2APlugin#2]
Hi,

Would it be possible to add multi-language support?
I would be able to provide a French translation.

Thank you in advance for your response.

Sincerely,
WikiJM

**Comment by inputstick** [comment]
Hi,
sure I'd be happy to add translation, I'll just need translations for all strings*.xml files:
https://github.com/inputstick/KP2APlugin/tree/master/KP2APlugin/src/main/res/values

Jakub Zawadzki

**Comment by wikijm** [comment]
Hi,

I just created a pull request to add the French translation.
Here it is: https://github.com/inputstick/KP2APlugin/pull/4

Sncerely,
WikiJM

**Comment by inputstick** [comment]
Great, thank you. I'll release update soon.
Do you want me to put some info/credits in "about app" section (name?, email?, website?)

Jakub Zawadzki

**Comment by wikijm** [comment]
Thank you very much for the proposal to add to the credits.
I would be happy to have this information added:

- Firstname LASTNAME: Jean-Marc ALBERT
- Website: https://github.com/wikijm

**Comment by inputstick** [comment]
ok, I added that to "About app" section and pushed the update to Google Play, it should be available in a few hours. Once again, thanks for the translation.

Jakub Zawadzki

**Comment by wikijm** [comment]
Hi Jakub,

Thanks a lot for this (time-spending, awesome answer and reaction, and stuff) 😃 
Feel free to contact me if new versions and features require translation to be done.

Sincerely,
WikiJM
